nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

packageExtensions:
  # awaiting fix: https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/issues/147
  "cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
      ts-node:
        optional: true
  "@endemolshinegroup/cosmiconfig-typescript-loader@*":
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
  "ts-node@*":
    peerDependenciesMeta:
      "@types/node":
        optional: true
      typescript:
        optional: true
