import Head from "next/head";
import { Inter } from "@next/font/google";
import home from "@/styles/Home.module.css";
import styles from "@/styles/PWReset.module.css";
import { useCallback, useRef, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [processing, setProcessing] = useState(false);
  const inputRef = useRef<HTMLInputElement>(null);
  const checkRef = useRef<HTMLInputElement>(null);
  const handleSubmit = useCallback(async () => {
    if (processing || !inputRef.current || !checkRef.current) {
      return;
    }

    const u = checkRef.current.checked
      ? "/api/auth/reset-fast"
      : "/api/auth/reset-slow";

    setProcessing(true);
    try {
      const resp = await fetch(u, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          email: inputRef.current.value,
        }),
      });
      const res = await resp.json();
      console.log(res);
    } catch (e) {
      console.error(e);
    } finally {
      setProcessing(false);
    }

    setProcessing(false);
  }, [processing]);

  return (
    <>
      <Head>
        <title>Password Reset Example - Taskless</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={home.main}>
        <div className={home.center}>
          <div className={`${styles.grid} ${styles["grid-2"]}`}>
            <h1 className={inter.className}>Reset Your Password</h1>
            <div
              className={`${styles.grid} ${styles["grid-3"]}`}
              style={{ opacity: processing ? 0.5 : 1 }}
            >
              <input
                className={styles.input}
                type="email"
                placeholder="your email"
                defaultValue="sample@example.com"
                ref={inputRef}
                readOnly={processing}
              />
              <label className={inter.className}>
                <input type="checkbox" ref={checkRef} /> Use Taskless
              </label>
              <button type="button" onClick={handleSubmit}>
                Forgot Password
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
